FROM ghcr.io/huggingface/text-embeddings-inference:1.5-grpc

RUN apt update && \
    apt upgrade -y && \
    apt install -y curl && \
    curl -sSL "https://github.com/fullstorydev/grpcurl/releases/download/v1.9.1/grpcurl_1.9.1_linux_x86_64.tar.gz" | tar -xz -C /usr/local/bin && \
    rm -rf /var/lib/apt/lists/*
RUN useradd --create-home --uid 1001 docker_user
RUN mkdir -p /data && chown -R 1001:1001 /data

ARG CACHEBUST="0"
RUN if [ "$CACHEBUST" != "0" ]; then \
        echo $CACHEBUST && \
        apt update && \
        apt upgrade -y && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*; \
    fi

USER docker_user
ENTRYPOINT []