services:
  rag-battle:
    build:
      args:
        DEV_ENV: 1
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./rag_battle:$WORKING_DIR/rag_battle"
      - "./main.py:$WORKING_DIR/main.py"