FROM vllm/vllm-openai:v0.8.4
RUN pip install vllm[audio]

RUN apt update && \
    apt upgrade -y && \
    apt install -y curl && \
    rm -rf /var/lib/apt/lists/*
RUN useradd --create-home --uid 1001 docker_user

ARG CACHEBUST="0"
RUN if [ "$CACHEBUST" != "0" ]; then \
        echo $CACHEBUST && \
        apt update && \
        apt upgrade -y && \
        apt-get clean && \
        rm -rf /var/lib/apt/lists/*; \
    fi

USER docker_user

ENTRYPOINT ["python3", "-m", "vllm.entrypoints.openai.api_server"]