import numpy as np
from typing import TypeVar
from dataclasses import dataclass


@dataclass
class RAGQuery:
    """
    Represents a Retrieval-Augmented Generation query.

    This class encapsulates all parameters needed for a RAG retrieval operation,
    including the text query, filtering tags, and configuration options.
    """

    query: str  # The natural language query text
    tags: list[str]  # Tags to filter documents by
    num_items: int  # Maximum number of items to retrieve
    remove_duplicates: bool = True  # Whether to deduplicate results


@dataclass
class DataItem:
    """
    Represents a document or content item in the RAG system.

    This class stores the content and metadata of items that can be retrieved
    during RAG operations. It includes the actual text content, a unique identifier,
    categorization tags, and an optional relevance score.
    """

    item_id: str  # Unique identifier for the item
    content: str  # The text content of the item
    tags: list[str]  # Categorization tags for filtering
    score: float | None = None  # Relevance score (populated during retrieval)


@dataclass
class DataItemWithEmbedding:
    """
    Extends DataItem with a vector embedding representation.

    This class is used internally for storing and manipulating items along with
    their vector representations generated by embedding models.
    """

    item: DataItem  # The base data item
    embedding: np.ndarray  # Vector embedding of the item's content


DataItemType = TypeVar("DataItemType", bound=DataItem)
DataItemWithEmbeddingType = TypeVar(
    "DataItemWithEmbeddingType", bound=DataItemWithEmbedding
)
